### ISSUE TITLE
The list of parameters with CaseReader and parametric.parameters.InputParameters doesnot match. 

### ISSUE THREAD

**Issue by tejalprabhu01** [pyansys/pyfluent#882]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

The list of parameters with CaseReader and parametric.parameters.InputParameters doesnot match. Please use attached file

![image](https://user-images.githubusercontent.com/97435870/190340284-f866eb02-5664-4c75-8fdd-64a36132e378.png)
[fluent_example.zip](https://github.com/pyansys/pyfluent/files/9572814/fluent_example.zip)

### 📝 Steps to reproduce

The steps are seen in attached screenshot

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
ansys-fluent-core
ansys-fluent-parametric
```

**Comment by tejalprabhu01** [comment]
@seanpearsonuk @mkundu1

**Comment by seanpearsonuk** [comment]
@tejalprabhu01 is this the same issue that @mkundu1 recently addressed in https://github.com/pyansys/pyfluent-parametric/pull/103? I don't know if you have the changes from that PR. Are the extra input paramaters in parametric just the non-parameter expressions that are now filtered out? Or do we still have an issue?

**Comment by tejalprabhu01** [comment]
@seanpearsonuk as I understand pyansys/pyfluent-parametric#103 fixed the filtering of the non-parameter expressions. But as you can see in the screenshot above, there are a lot of parameters that are non-expression type and are still not listed by CaseReader. So I think this is some other issue.

**Comment by seanpearsonuk** [comment]
@tejalprabhu01 CaseReader behaviour is correct.  This is the expression data in the case.  I have indented those which are labeled as (input) parameters>  
```
(named-expressions (
((name . "xc_cold") (definition . "1 [m]") (description . "x-coordinate of centroid of cold inlet") (parameterid . "") (parametername . "") (parameter . #f)) 
((name . "xc_hot") (definition . "1 [m]") (description . "x-coordinate of centroid of hot inlet") (parameterid . "") (parametername . "") (parameter . #f)) 
((name . "zc_cold") (definition . "-1 [m]") (description . "z-coordinate centroid of cold inlet") (parameterid . "") (parametername . "") (parameter . #f)) 
((name . "zc_hot") (definition . "1[m]") (description . "z-coordinate of center of hot inlet") (parameterid . "") (parametername . "") (parameter . #f)) 
((name . "yc_hot") (definition . "2.3[m]") (description . "y-coordinate of center of hot inlet") (parameterid . "") (parametername . "") (parameter . #f)) 
((name . "yc_cold") (definition . "-2.3[m]") (description . "y-coordinate of center of cold inlet") (parameterid . "") (parametername . "") (parameter . #f)) 
((name . "rc_hot") (definition . "sqrt((x-xc_hot)**2+(z-zc_hot)**2)") (description . "") (parameterid . "") (parametername . "rc_hot") (parameter . #f)) 
((name . "swirl_loc_hot") (definition . "swirl_max_hot*(1-((rc_hot/(radius_hot_inlet/2))-1)**2)") (description . "") (parameterid . "") (parametername . "swirl_loc_hot") (parameter . #f)) 
    ((name . "swirl_max_hot") (definition . "0.1 [m s^-1]") (description . "") (parameterid . "") (parametername . "swirl_max_hot") (parameter . #t))
    ((name . "vel_hot") (definition . "0.1 [m s^-1]") (description . "") (parameterid . "") (parametername . "vel_hot") (parameter . #t)) 
((name . "radius_cold_inlet") (definition . "0.5 [m]") (description . "") (parameterid . "") (parametername . "radius_cold_inlet") (parameter . #f)) 
((name . "radius_hot_inlet") (definition . "0.5 [m]") (description . "") (parameterid . "") (parametername . "radius_hot_inlet") (parameter . #f)) 
((name . "rc_cold") (definition . "sqrt((x-xc_cold)**2 + (z-zc_cold)**2)") (description . "") (parameterid . "") (parametername . "rc_cold") (parameter . #f)) 
    ((name . "vel_cold") (definition . "0.1 [m s^-1]") (description . "") (parameterid . "") (parametername . "vel_cold") (parameter . #t)) 
    ((name . "swirl_max_cold") (definition . "0.1 [m s^-1]") (description . "peak swirl velocity in parabolic profile") (parameterid . "") (parametername . "swirl_max_cold") (parameter . #t)) 
((name . "swirl_loc_cold") (definition . "swirl_max_cold*(  1-(  (rc_cold/(radius_cold_inlet/2))-1   )**2   )") (description . "") (parameterid . "") (parametername . "swirl_loc_cold") (parameter . #f))))
```

**Comment by tejalprabhu01** [comment]
@seanpearsonuk Thanks for the clarification. The confusion arises because from optiSLang point of view any parameter that has a value and not expression is treated as input parameter. In the list above we can see for example "xc_cold" etc also looks like name-value pair and therefore we expected them to be a part of input parameter list and not as an expression data. 
But if that is not the case for Fluent then it is okay. we can close this ticket.

**Comment by mkundu1** [comment]
![image](https://user-images.githubusercontent.com/94432368/190661154-7f5a20bb-3d4a-4b14-8894-20447fd64c11.png)
![image](https://user-images.githubusercontent.com/94432368/190661261-d4aab9e7-dce7-4630-8d81-b17c2ad2b281.png)

As per Fluent, `vel_cold` is an input parameter, but `xc_cold` is not. So both `CaseReader` and `InputParameters` are returning the correct set as per Fluent.
